version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: carpool_db_completed_v1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./carpool-backend
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carpool_db_completed_v1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      # Add your Twilio and JWT env vars here, or use a .env file
      # TWILIO_ACCOUNT_SID: your_sid
      # TWILIO_AUTH_TOKEN: your_token
      # TWILIO_WHATSAPP_FROM: whatsapp:+1234567890
      # TEST_PHONE_NUMBER: your_test_number
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: