version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: carpool-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: carpool_db
      MYSQL_USER: carpool_user
      MYSQL_PASSWORD: carpool_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - carpool-network

  redis:
    image: redis:alpine
    container_name: carpool-redis
    ports:
      - "6379:6379"
    networks:
      - carpool-network

  backend:
    build: .
    container_name: carpool-backend
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=carpool_user
      - DB_PASSWORD=carpool_pass
      - REDIS_HOST=redis
      - JWT_SECRET=myVerySecretKeyForJWTTokenGenerationThatNeedsToBeAtLeast256Bits
    networks:
      - carpool-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data:

networks:
  carpool-network:
    driver: bridge
